// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://humenrpjbtdqpcrnuoff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1bWVucnBqYnRkcXBjcm51b2ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NzI4ODMsImV4cCI6MjA3MzM0ODg4M30.Vp2sfrOd5ae4TgaVs9XfUvawRNjslPMzEvrWJEuDCnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});